{% set name = "dream3d-conda" %}
{% set version = "1.4.0" %}
{% if DREAM3D_PLUGINS is defined %}
  {% set plugin_list = DREAM3D_PLUGINS.split(';') %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/bluequartzsoftware/CMP.git
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: CMP
  - git_url: https://github.com/bluequartzsoftware/SIMPL.git
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: SIMPL
  - git_url: https://github.com/bluequartzsoftware/SIMPLView.git
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: SIMPLView
  - git_url: https://github.com/bluequartzsoftware/H5Support.git
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: H5Support
  - git_url: https://github.com/bluequartzsoftware/EbsdLib.git
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: EbsdLib
  - git_url: https://github.com/bluequartzsoftware/DREAM3D.git
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: DREAM3D
  - git_url: https://github.com/DREAM3D/DREAM3D_Data.git
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: DREAM3D_Data
  - git_url: https://github.com/DREAM3D/DREAM3DReview.git
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: DREAM3D_Plugins/DREAM3DReview
  - git_url: https://github.com/DREAM3D/UCSBUtilities.git
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: DREAM3D_Plugins/UCSBUtilities
  - git_url: https://github.com/bluequartzsoftware/ITKImageProcessing.git
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: DREAM3D_Plugins/ITKImageProcessing
  - git_url: https://github.com/bluequartzsoftware/SimulationIO.git
    git_depth: 1 # (Defaults to -1/not shallow)
    folder: DREAM3D_Plugins/SimulationIO
  - path: Conda
    folder: DREAM3D/Conda

build:
  number: 0
  script_env:
    - DREAM3D_PLUGINS={{ DREAM3D_PLUGINS|default("") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - "cmake>=3.16"
    - ninja
    - git
    - {{ cdt('mesa-libgl-devel') }} # [linux]
    - {{ cdt('mesa-dri-drivers') }} # [linux]
    - {{ cdt('libselinux') }} # [linux]
    - {{ cdt('libxdamage') }} # [linux]
    - {{ cdt('libxxf86vm') }} # [linux]
    - {{ cdt('libxext') }} # [linux]
  host:
    - python
    - mkdocs
    - mkdocs-material
    - mkdocs-material-extensions
    - cpp-filesystem
    - eigen
    - hdf5=1.10.5
    - libharu
    - libitk
    - libitk-devel
    - "numpy>=1.16"
    - mypy
    - "pybind11>=2.6"
    - "qt>=5.9"
    - qwt
    - tbb
    - tbb-devel
    - xorg-libxfixes # [linux]
  run:
    - python
    - numpy
    - hdf5=1.10.5
    - libharu
    - libitk
    - qt
    - qwt
    - tbb
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.14") }} # [osx and x86_64]

about:
  home: http://dream3d.bluequartz.net/
  license: BSD
  summary: DREAM.3D consists of data analysis tools (Filters) that allow for the construction of customized workflows (Pipelines) to analyze data.
